# path
export PATH="$HOME/.local/bin:$PATH"
typeset -U PATH path

# pure
fpath+=/usr/local/pure
autoload -U promptinit; promptinit
zstyle :prompt:pure:git:stash show yes
#zstyle :prompt:pure:path color blue
#zstyle ':prompt:pure:prompt:*' color cyan
prompt pure

# aliases
[ -f "$ZDOTDIR/aliases" ] && source "$ZDOTDIR/aliases"

# tab completion
autoload -Uz compinit
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|?=**'
zmodload zsh/complist
compinit
_comp_options+=(globdots)		# Include hidden files.

# dir completion
setopt  autocd autopushd

# kitty completion
kitty + complete setup zsh | source /dev/stdin

# pywal
(cat ~/.cache/wal/sequences &)

# mode: vi (v) or emacs (e)
bindkey -e
export KEYTIMEOUT=1

# edit line in vim with ctrl-X, ctrl-e:
autoload edit-command-line; zle -N edit-command-line
bindkey '^x^e' edit-command-line

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# xterm/urxvt cursor (beam)
# 35 (blink), 36 (no blink)
echo -e -n "\x1b[\x36 q"

# ncmpcpp (ctrl+\)
ncmpcppShow() {
  BUFFER="ncmpcpp -q"
  zle accept-line
}
zle -N ncmpcppShow
bindkey '^\' ncmpcppShow

# lfcd (ctrl+])
lfcd="$HOME/.config/lf/lfcd.sh"
    if [ -f "$lfcd" ]; then
    source "$lfcd"
fi
bindkey -s '^]' 'lfcd\n'

# functions
source ~/.config/zsh/functions/fzf-edit 2>/dev/null
source ~/.config/zsh/functions/fzf-kill 2>/dev/null
source ~/.config/zsh/functions/fzf-man 2>/dev/null

# plugins
source /usr/local/oh-my-zsh/plugins/extract/extract.plugin.zsh 2>/dev/null
source /usr/local/oh-my-zsh/plugins/command-not-found/command-not-found.plugin.zsh 2>/dev/null
source /usr/local/oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh 2>/dev/null
source /usr/local/oh-my-zsh/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh 2>/dev/null