# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# path
typeset -U PATH path

# omz fix
export ZSH_DISABLE_COMPFIX=true

# oh-my-zsh path
export ZSH="/usr/share/oh-my-zsh"

# zsh theme
#ZSH_THEME="p10k"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# case-sensitive completion
#CASE_SENSITIVE="true"

# history
HIST_STAMPS="yyyy-mm-dd"

# plugins
plugins=(
#colored-man-pages
command-not-found
extract
#zsh-autocomplete
zsh-autosuggestions
zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# aliases
[ -f "$ZDOTDIR/aliases" ] && source "$ZDOTDIR/aliases"

# to customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# completion for kitty
kitty + complete setup zsh | source /dev/stdin

# pywal
(cat ~/.cache/wal/sequences &)
source ~/.cache/wal/colors-tty.sh

# vi (v) or emacs (e)
#bindkey -v
#export KEYTIMEOUT=1

# edit line in vim with ctrl-X, ctrl-e:
autoload edit-command-line; zle -N edit-command-line
bindkey '^x^e' edit-command-line

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# fzf options
export FZF_DEFAULT_COMMAND="fd -H -L -E '.git' -E '.cache'"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="$FZF_DEFAULT_COMMAND -t d"
export FZF_DEFAULT_OPTS="
--layout=reverse-list
--info=inline
--height=50%
--multi
--border=sharp
--preview-window=:hidden
--preview '([[ -f {} ]] && (bat --style=numbers --color=always {} || cat {})) || ([[ -d {} ]] && (tree -C {} | less)) || echo {} 2> /dev/null | head -200'
--prompt='∼ ' --pointer='▶' --marker='✓'
--bind '?:toggle-preview'
--bind 'ctrl-a:select-all'
"
#--bind 'ctrl-y:execute-silent(echo {+} | pbcopy)'
#--bind 'ctrl-e:execute(echo {+} | xargs -o vim)'

# starship
#export STARSHIP_CONFIG=~/.config/starship/starship.toml
#export STARSHIP_CACHE=~/.cache/starship
#eval "$(starship init zsh)"

# pure
fpath+=$HOME/work/pure
autoload -U promptinit; promptinit
zstyle :prompt:pure:git:stash show yes
#zstyle :prompt:pure:path color blue
#zstyle ':prompt:pure:prompt:*' color cyan
prompt pure

# xterm/urxvt cursor (beam)
# 35 (blink), 36 (no blink)
echo -e -n "\x1b[\x36 q"

# ncmpcpp (ctrl+\)
ncmpcppShow() {
  BUFFER="ncmpcpp"
  zle accept-line
}
zle -N ncmpcppShow
bindkey '^\' ncmpcppShow

# lfcd (ctrl+])
lfcd="$HOME/.config/lf/lfcd.sh"
    if [ -f "$lfcd" ]; then
    source "$lfcd"
fi
bindkey -s '^]' 'lfcd\n'

# git helper
gacp() {
  git add .
  git commit -m "$1"
  git push
}

# functions
source ~/.config/zsh/functions/fzf-edit 2>/dev/null
source ~/.config/zsh/functions/fzf-kill 2>/dev/null
source ~/.config/zsh/functions/fzf-man 2>/dev/null

# gitstatus
# export POWERLEVEL9K_DISABLE_GITSTATUS=true
