#!/bin/sh

while read file
do
        case "$1" in
        "w")
		xwallpaper --zoom "$file" & ;;
	"r")
		convert -rotate 90 "$file" "$file" ;;
	"R")
		convert -rotate -90 "$file" "$file" ;;
	"f")
		convert -flop "$file" "$file" ;;
	"y")
		echo -n "$file" | tr -d '\n' | xclip -selection clipboard &&
		notify-send "$file copied to clipboard" & ;;
	"Y")
		readlink -f "$file" | tr -d '\n' | xclip -selection clipboard &&
			notify-send "$(readlink -f "$file") copied to clipboard" & ;;
	"g")	
		gimp "$file" ;;
	"i")	
		notify-send "File information" "$(mediainfo "$file")" ;;

	"1")
		wal -i "$file" --backend colorthief && wal-extras.sh ;;
	"2")
		wal -i "$file" --backend faster_colorthief && wal-extras.sh ;;
	"3")
		wal -i "$file" --backend haishoku && wal-extras.sh ;;
	"4")
		wal -i "$file" --backend wal && wal-extras.sh ;;
        esac
done