#!/bin/sh

# autostart apps
picom.sh
#wal -R &
xautolock.sh &
redshift.sh &
hsetroot -fill ~/.fluxbox/wallpaper.jpg
xset +fp ~/.fonts/misc/

# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

# fluxbox
exec fluxbox -no-slit -log "~/.fluxbox/log"
