#!/bin/sh

# start
picom --experimental-backends --config ~/.config/picom/picom.conf &
wal -R -o wal-extras.sh &
xautolock -time 10 -locker 'lock.sh' -killer 'systemctl suspend' -corners +0-0 -cornerdelay 1 &
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
systemctl --user import-environment; systemctl --user restart redshift

# glava
w=$(( $(xdotool getdisplaygeometry | awk '{print $1}') / 2 ))
h=$(( $(xdotool getdisplaygeometry | awk '{print $2}') ))
x=$(( $(xdotool getdisplaygeometry | awk '{print $1}') / 2 - (w/2) ))
sed -i "s|#request setgeometry.*$|#request setgeometry $x 0 $w $h|g" ~/.config/glava/rc.glsl

# cwm
exec /usr/local/bin/cwm
