#!/bin/sh

# reset all rules
bspc rule -r "*"

# set cursor
xsetroot -cursor_name left_ptr

# autostart
picom --config ~/.config/bspwm/picom.conf &
redshift.sh &
xautolock.sh &
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
polybar-bspwm.sh &
pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/bspwm/sxhkdrc &

# monitors
bspc monitor eDP-1 -d 1 2 3 4 5

# desktop
bspc config automatic_scheme 		longest_side
bspc config pointer_modifier 		Mod4
bspc config initial_polarity        	second_child
bspc config split_ratio          	0.50

bspc config borderless_monocle   	true
bspc config gapless_monocle      	false
bspc config single_monocle             true

bspc config focus_follows_pointer 	true

bspc config top_padding 		0
bspc config bottom_padding 		0
bspc config left_padding 		0
bspc config right_padding 		0
bspc config border_width 		1
bspc config window_gap                  10

# colors
. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color 	"$color8"
bspc config active_border_color 	"$color2"
bspc config focused_border_color 	"$color2"
bspc config presel_feedback_color
bspc config urgent_border_color	"$color1"

# rules
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
