# prompt
add_newline = true

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[[battery.display]]
threshold = 30
style = "bold red"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold green)"
disabled = false

[directory]
read_only = " "

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[hostname]
ssh_only = true
format =  "on [$hostname](bold red) "
disabled = false

[memory_usage]
threshold = -1
format = "$symbol [${ram_pct}]($style) "
style = "bold dimmed green"
symbol = ""
disabled = true

[python]
symbol = " "

[username]
format = "[$user]($style) "
disabled = false
