# prompt
format = "$all"
add_newline = true

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[[battery.display]]
threshold = 30
style = "bold red"

[character]
error_symbol = "[✗](bold red) "
#vicmd_symbol = "[V](bold green) "

[directory]
read_only = " "

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[hostname]
ssh_only = true
format =  "[$hostname](bold red) "
disabled = false

[memory_usage]
disabled = true
threshold = -1
style = "bold dimmed green"
symbol = " "

[python]
symbol = " "

[username]
style_user = "white bold"
style_root = "black bold"
format = "user: [$user]($style) "
disabled = true
show_always = true
