#!/bin/bash

# Set startup apps
sxhkd -c $HOME/.config/berry/sxhkdrc &
nitrogen --restore &
redshift-gtk.sh &
xautolock.sh &
picom.sh &
dunst &
~/.config/polybar/launch-ewmh.sh &
mpd.sh &

# Set decoration geometry
berryc border_width       1
berryc inner_border_width 5
berryc title_height       22
berryc top_gap            30

# Set decoration colors
berryc focus_color          
berryc unfocus_color	    
berryc inner_focus_color    565679
berryc inner_unfocus_color  3D3D56
berryc text_focus_color     000000
berryc text_unfocus_color   111111

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "monospace-7.5"
