#!/bin/sh

# Set startup apps
sxhkd -c $HOME/.config/berry/sxhkdrc &
polybar-2.sh &
#nitrogen --restore &
redshift.sh &
xautolock.sh &
#picom.sh &
dunst &
libinput-gestures &
wal -R -o "wal-berry.sh" -o "wal-dunst.sh" &
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

# Set decoration geometry
berryc border_width       0
berryc inner_border_width 4
berryc title_height       26
berryc top_gap            38

# Set decoration colors
berryc focus_color          
berryc unfocus_color        
berryc inner_focus_color    565679
berryc inner_unfocus_color  3D3D56
berryc text_focus_color     000000
berryc text_unfocus_color   111111

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "Iosevka Term-7.5"
