#!/bin/sh

# Set decoration geometry
berryc border_width         0
berryc inner_border_width   0
berryc title_height         24
berryc edge_gap             0 50 0 0
berryc decorate_new 	    "true"

# Set decoration colors
berryc focus_color          
berryc unfocus_color        
berryc inner_focus_color    565679
berryc inner_unfocus_color  3D3D56
berryc text_focus_color     000000
berryc text_unfocus_color   111111

# Other options
berryc smart_place  "true"
berryc draw_text    "true"
berryc edge_lock    "true"
berryc set_font     "scientifica-8:bold"

# wal
wal -q -R -o wal-extras.sh

# sxhkd
sxhkd -c "$HOME"/.config/berry/sxhkdrc "$HOME"/.config/sxhkd/sxhkdrc.common &

# redshift
systemctl --user import-environment; systemctl --user restart redshift

# picom
picom --experimental-backends --config ~/.config/picom/picom.conf &
# picom --config ~/.config/picom/picom-xr.conf &

# polkit
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# lock
xscreensaver --no-splash &
xautolock -time 10 -locker 'xscreensaver-command -lock' -killer 'systemctl suspend' -corners +0-0 -cornerdelay 2 &

# status bar
lemonbar-current &

# touchegg
touchegg &

# glava
w=$(( $(xdotool getdisplaygeometry | awk '{print $1}') / 2 ))
h=$(( $(xdotool getdisplaygeometry | awk '{print $2}') ))
x=$(( $(xdotool getdisplaygeometry | awk '{print $1}') / 2 - (w/2) ))
sed -i "s|#request setgeometry.*$|#request setgeometry $x 0 $w $h|g" ~/.config/glava/rc.glsl
