#!/bin/bash

# colours
. "$HOME/.cache/wal/colors.sh"

# picom
picom --experimental-backends --config ~/.config/picom/picom.conf &
# picom --config ~/.config/picom/picom-xr.conf &

# polkit
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# lock
xautolock -time 10 -locker 'lock.sh' -killer 'systemctl suspend' -corners 00-+ &

# redshift
systemctl --user import-environment
systemctl --user restart redshift.service

# bg
# bash $HOME/.fehbg &
xwallpaper --zoom $wallpaper &

# wal
wal -q -R -o -wal-extras.sh &

# lemonbar
lemonbar-current &

# polybar
#pb-nf.sh &

# touchegg
touchegg.sh &