#!/bin/sh

# picom
picom --experimental-backends --config ~/.config/picom/picom.conf &
# picom --config ~/.config/picom/picom-xr.conf &

# polkit
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# lock
xscreensaver --no-splash &
xautolock -time 10 -locker 'xscreensaver-command -lock' -killer 'systemctl suspend' -corners +0-0 -cornerdelay 1 &

# redshift
systemctl --user import-environment; systemctl --user restart redshift

# bg
bash "$HOME"/.fehbg &

# wal
wal -R -o wal-extras.sh

# statusbar
# polybar-current &

# glava
glava.sh &
