#!/bin/sh

# picom
picom --experimental-backends --config ~/.config/picom/picom.conf &
# picom --config ~/.config/picom/picom-xr.conf &

# polkit
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# lock
xautolock -time 10 -locker 'lock.sh' -killer 'systemctl suspend' -corners 00-+ &

# redshift
systemctl --user import-environment; systemctl --user restart redshift

# bg
bash "$HOME"/.fehbg &

# wal
wal -q -R -o -wal-extras.sh

# status bar
polybar-current &

# glava
sed -i "s|#request setgeometry.*$|#request setgeometry 0 0 1920 1080|g" ~/.config/glava/rc.glsl